### PR TITLE
Add metrics of disk usage

### PR DESCRIPTION
**Pull request by whywaita**
This PR adds a new feature that metrics for disk usage.

You can see an example in [Actions of my repo](https://github.com/whywaita/actions-runner-images-lxd/actions/runs/6565156388).

### CODE REVIEW

**Comment by whywaita** [comment]
Hi @rwxdash, What do you think about this change?

**Comment by echoix** [comment]
I’d be interested in something like this, since we regularly have to debug remaining disk space in building the various Megalinter images.

**Comment by serkan-ozal** [comment]
Hi @whywaita,

Thanks for your contribution and sorry for late reply. Could you please rebase your PR with latest changes?

**Comment by whywaita** [comment]
@serkan-ozal I'm done.

**Comment by serkan-ozal** [comment]
Hi @whywaita,

I have seen that you have deleted process tracer binaries (`proc_tracer_ubuntu-20` and `proc_tracer_ubuntu-22`) in your PR. They are required eBPF executables to trace process activities. Was it intentional? If so, what was the reason?

**Comment by serkan-ozal** [comment]
@whywaita 
Other than deleted files, the overall PR looks good.

**Comment by serkan-ozal** [comment]
@rwxdash could you please review too

**Comment by whywaita** [comment]
@serkan-ozal 

> I have seen that you have deleted process tracer binaries (proc_tracer_ubuntu-20 and proc_tracer_ubuntu-22) in your PR. They are required eBPF executables to trace process activities. Was it intentional? If so, what was the reason?

Oh, sorry. I have no reason for the deleted binaries. I deleted a `dist` directory because I thinked only code-generated files.

**Comment by rwxdash** [comment]
Looks good to me as well, thank you @whywaita.

**Comment by whywaita** [comment]
You can check it at https://github.com/whywaita/actions-runner-images-lxd/actions/runs/8133293638. (CI is a failure 😿 but metrics are correct!)

**Review by serkan-ozal — APPROVED** [review]

**Review by rwxdash — APPROVED** [review]

**Comment by serkan-ozal** [comment]
Thanks for your contribution @whywaita.

**Comment by whywaita** [comment]
Thank you!

**Pull request merged**
