### PR TITLE
Node runtime and package updates

### PR DESCRIPTION
**Pull request by jjosef**
Fixes https://github.com/catchpoint/workflow-telemetry-action/issues/55

### CODE REVIEW

**Comment by jjosef** [comment]
> Hey @jjosef, thank you for opening the PR.
> 
> Can you run `npm run format` and commit the linting changes? Since `prettier` is upgraded with this PR, I assume some of the default conf have changed and causing the build to fail.
> 
> Thanks.

Done!

**Comment by jjosef** [comment]
Also upgraded `ncc` and `typescript` packages. seems to build fine now

**Comment by rwxdash** [comment]
Thank you @jjosef. Looks good to me and the updates are probably OK, but just to be sure, have you had any chance to test the action from your fork to see things are working? If not, I'll try to make some time to test it out and approve/merge from there.

cc\ @serkan-ozal

**Comment by jjosef** [comment]
> Thank you @jjosef. Looks good to me and the updates are probably OK, but just to be sure, have you had any chance to test the action from your fork to see things are working? If not, I'll try to make some time to test it out and approve/merge from there.
> 
> cc\ @serkan-ozal

Yes I am using it in production for my company currently

**Comment by rwxdash** [comment]
Awesome, thank you.

**Review by rwxdash — APPROVED** [review]
Looks good to me. Thank you, @jjosef!

**Comment by fwilhe** [comment]
Merging this PR into main would be appreciated.

We are using a fork of this action but i don't want unnecessary large diverges from upstream, so I'd like to use the commit(s) from the main branch.

Thank you

**Comment by rwxdash** [comment]
Merging it, as it looks OK at this stage and no further review required.

Thank you.

**Comment by johanneswuerbach** [comment]
@rwxdash any chance to get this released? Maybe as v2?

**Comment by johanneswuerbach** [comment]
Most actions I've seen released the node upgrade as major (e.g. [actions/checkout](https://github.com/actions/checkout/blob/main/CHANGELOG.md#v400)) or [docker/build-push-action](https://github.com/docker/build-push-action/releases/tag/v5.0.0)). I guess this is mainly due to the fact that actions can also be used on self-hosted runners / self-hosted github and there the new node version might not be available yet.

**Comment by rwxdash** [comment]
Hey @johanneswuerbach @serkan-ozal,

Yes, my initial thought was to release it as v2 as well since it's the convention I see from other actions. If v2 sounds good @serkan-ozal, I can prepare the action for it and we can do the release.

**Comment by serkan-ozal** [comment]
Hmm, OK makes sense. @rwxdash could you please release as v2

**Comment by rwxdash** [comment]
[**v2**](https://github.com/catchpoint/workflow-telemetry-action/releases/tag/v2.0.0) has been released. Thank you all for pushing this through!

**Pull request merged**
