### PR TITLE
README: Add permissions to sample code

### PR DESCRIPTION
**Pull request by massongit**
This Actions needs `pull-requests: write` permission for commenting on pull request.
Therefore, I add this permission to sample code in README.

### CODE REVIEW

**Comment by massongit** [comment]
The faliture in CI is expected to be resolved by merging https://github.com/catchpoint/workflow-telemetry-action/pull/62.

**Comment by massongit** [comment]
The CI `build` failed because you didn't approve to run CI and didn't run it for pull requests from the forked repository before merging.
Therefore, in such cases, please approve and run it before merging.

**Comment by massongit** [comment]
The faliture in CI is resolved.

**Review by rwxdash — APPROVED** [review]

**Review by suleymanbarman — APPROVED** [review]

**Comment by rwxdash** [comment]
Thank you for the contribution, @massongit.

**Pull request merged**
